# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        manager:
            id: sonata_authorization.security.user.manager_user_provider
        app_users:
            entity:
                class:    App\Entity\User
                property: email
        app_carriers:
            entity:
                class:    App\Entity\Carrier
                property: email
        app_all:
            chain:
                providers: [app_users, app_carriers]
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy:      true
            pattern:   ^/admin
            provider:  manager
            logout:
                path:   _user_admin_security_logout
                target: _user_admin_security_login
            form_login:
                login_path:                     _user_admin_security_login
                check_path:                     _user_admin_security_login
                enable_csrf:                    true
                csrf_parameter:                 _csrf_token
                csrf_token_id:                  authenticate
                default_target_path:            sonata_admin_dashboard
                always_use_default_target_path: false
                username_parameter:             email
                password_parameter:             password
            stateless: false
            remember_me:
                secret:             '%kernel.secret%'
                lifetime:           604800        # 1 week
                always_remember_me: true
                # storage of tokens:
                signature_properties: [ 'password' ]
                token_provider:
                    doctrine: true
        api:
            pattern:   ^/api
            stateless: true
            provider:  app_all
            jwt: ~
        main:
            pattern:      ^/
            lazy:         true
            stateless:    true
            provider:     app_all
            jwt:          ~
            entry_point:  App\Security\UserAuthenticationEntryPoint

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, role: PUBLIC_ACCESS }
        - { path: ^/admin/login_check$, role: PUBLIC_ACCESS }
        - { path: ^/admin,  role: ROLE_ADMIN }
        - { path: ^/api/auth/login$, role: PUBLIC_ACCESS }
        - { path: ^/api/auth/refresh$, role: PUBLIC_ACCESS }
        - { path: ^/api/auth/logout$, role: PUBLIC_ACCESS }
        - { path: ^/api/auth/me$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout$, role: PUBLIC_ACCESS }
        - { path: ^/files/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/carrier/, role: ROLE_CARRIER }
        - { path: ^/.*, role: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_USER:
            - ROLE_USER
        ROLE_MANAGER:
            - ROLE_USER
        ROLE_CARRIER:
            - ROLE_CARRIER

